### ISSUE TITLE
R says this is not an R package? 

### ISSUE THREAD

**Issue by abnormally-distributed** [jakubmazanec/bayesian-efa#1]
I see a file called efa.R and a reference to the rjags and psych packages, so I assumed this is an R package. Yet I get this error:

```
Downloading GitHub repo jakubmazanec/bayesian-efa@master
from URL https://api.github.com/repos/jakubmazanec/bayesian-efa/zipball/master
Error: Does not appear to be an R package (no DESCRIPTION)
```

Is this indeed an R package, and if so, how can I download it?

**Comment by jakubmazanec** [comment]
This is not an R package, just some R code implementing bayesian EFA as described in Lockwood, J. R., Savitsky, T. D., & McCaffrey, D. F. (2015). Inferring constructs of effective teaching from classroom observations: An application of Bayesian exploratory factor analysis without restrictions. The Annals of Applied Statistics, 9(3), 1484–1509.

If you're looking for an R package to perform BEFA , you can try this one: https://cran.r-project.org/web/packages/BayesFM/BayesFM.pdf (but it's based on a slightly different approach how to solve problems with model identification).
